// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7I9eXczT5UD3t6dEimcRqckEsmoK7gI',
    appId: '1:993646711365:web:c39c075dcaa7ef9d40c92c',
    messagingSenderId: '993646711365',
    projectId: 'puzzleflutterapp',
    authDomain: 'puzzleflutterapp.firebaseapp.com',
    databaseURL: 'https://puzzleflutterapp-default-rtdb.firebaseio.com',
    storageBucket: 'puzzleflutterapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoHxQWKgRKAAETBdZO82GDFx38Sah0qL4',
    appId: '1:993646711365:android:2752a6a0812a86a840c92c',
    messagingSenderId: '993646711365',
    projectId: 'puzzleflutterapp',
    databaseURL: 'https://puzzleflutterapp-default-rtdb.firebaseio.com',
    storageBucket: 'puzzleflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBes09ioWUHcYp8C_HM_PURa-4-ep8GiUs',
    appId: '1:993646711365:ios:884cf7812caf2ba540c92c',
    messagingSenderId: '993646711365',
    projectId: 'puzzleflutterapp',
    databaseURL: 'https://puzzleflutterapp-default-rtdb.firebaseio.com',
    storageBucket: 'puzzleflutterapp.appspot.com',
    iosClientId: '993646711365-fd08fu8rof8tfq3o93bepoui8u5cesg0.apps.googleusercontent.com',
    iosBundleId: 'app.web.groons.puzzleapp',
  );
}
